import "./globals.css";
import SideNav from "components/SideNav";
import { ReactNode } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <SideNav />
          <main className="flex-1 p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
